matches:
  - trigger: ":espanso"
    replace: "Hi there!"

  - trigger: ":date"
    replace: "{{mydate}}"
    vars:
      - name: mydate
        type: date
        params:
          format: "%m/%d/%Y"

  - trigger: ":shell"
    replace: "{{output}}"
    vars:
      - name: output
        type: shell
        params:
          cmd: "echo 'Hello from your shell'"

  - trigger: ":action"
    replace: "export const someAction = async ({ state, effects, actions }: Context) => { };"

  - trigger: ":ormGet"
    replace: |
      export const ormGet = async ({ state, effects, actions }: Context) => {
        const array = await effects.orm
          .getRepository()
          .createQueryBuilder("")
          .getMany();

        console.log("ormArray");
        console.log(array);
      };

  - trigger: ":page"
    replace: |
      import React from "react";
      import { useActions, useAppState } from "../overmind";

      const Page = () => {
        return (
          <>
          </>
        );
      };
      export default Page;

